server:
  port: 80

spring:
  application:
    name: cloud-order-service  # 服务注册名

eureka:
  client:
    register-with-eureka: true #我们是服务端需要向注册服务中心注册自己
    fetch-registry: true #true抓取已有的注册信息，默认为true，单点无所谓，集群必须为true才能配合ribbon使用
    service-url:
      #defaultZone: http://localhost:7001/eureka #单机版
      defaultZone: http://eureka7001.com:7001/eureka, or http:/eureka7002.com:7002/eureka #集群版
  instance:
    instance-id: order80 #Eureka服务名
    prefer-ip-address: true #为true访问路径可以显示ip